config: 
  target: 'https://jsonplaceholder.typicode.com'
  phases: 
    - duration: 5
      arrivalRate: 5
      name: 'Warm up'
    - duration: 10
      arrivalRate: 5
      rampTo: 50
      name: 'Ramp up'
    - duration: 30
      arrivalRate: 50
      name: 'Max load'
  payload: 
    path: 'payloads/keywords.csv'
    field:
      - 'key'
scenarios:
  - name: "Search and Update"
    flow: 
      - get:
          url: '/posts'
          body: ''
          capture: 
            - json: "$[0].id"
              as: "id"
      # - log: "$[0].id: {{ id }}"
      - think: 3
      - get:
          url: "/posts/{{ id }}"

